---
dxr:
  www_root: '/'
  workers: 4
  default_tree: 'mozilla-central'
  disabled_plugins: ''
  enabled_plugins: '*'
  es_hosts:
    - http://node47.bunker.scl3.mozilla.com:9200/
    - http://node48.bunker.scl3.mozilla.com:9200/
    - http://node49.bunker.scl3.mozilla.com:9200/
  es_catalog_replicas: 4
  es_catalog_index: 'dxr_catalog'
  es_index: 'dxr_hot_{format}_{tree}_{unique}'
  es_alias: 'dxr_{format}_{tree}'
  es_indexing_timeout: 120
  es_refresh_interval: 30

defaults:
  disable: false
  schedule: 'H H/4 * * *'
  quiet_period: 3600
  job_weight: 1
  build_command: ''   # DXR's default is 'make ...'
  mail_rcpts: fubar@mozilla.com
  docker_img: 'quay.io/fubar/ubuntu-indexer:latest'
  docker_vol: '/data/dxr_data:/builds/dxr-build-env/src'
  cross_tree: false
  dxr_plugins:
    - plugin: 'python'
      python_path: '/builds/dxr-build-env/venv/lib/python2.7/site-packages'
    - plugin: 'buglink'
      name: 'bugzilla'
      url: 'https://bugzilla.mozilla.org/show_bug.cgi?id=%s'
      regex: '"(?i)bug\s+#?([0-9]+)"'

trees:
  - name: 'mozilla-central'
    url: 'https://hg.mozilla.org/mozilla-central'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && ./mach mercurial-setup -u && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'

  - name: 'comm-central'
    url: 'https://hg.mozilla.org/comm-central'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    ignore_patterns: 'all-tests.json .hg .git CVS .svn .bzr .deps .libs .DS_Store .nfs* *~ ._* *.pyc'
    build_command: 'cd $source_folder && python client.py checkout && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --enable-application=mail'
      - 'ac_add_options --disable-optimize'
      - 'ac_add_options --disable-elf-hack'
      - 'ac_add_options --enable-default-toolkit=cairo-gtk3'

  - name: 'build-central'
    url: 'https://hg.mozilla.org/build/'
    subpath: 'build'
    job_weight: 2
    build_command: ''
    cross_tree: true

  - name: 'hgcustom_version-control-tools'
    url: 'https://hg.mozilla.org/hgcustom/version-control-tools'

  - name: 'rust'
    url: 'https://github.com/rust-lang/rust.git'
    schedule: 'H H/6 * * *'
    quiet_period: 14400
    job_weight: 4
    build_command: 'cd $source_folder && ./configure --disable-libcpp --enable-ccache --enable-clang && make -j4'
    plugins:
      - plugin: 'buglink'
        name: 'github'
        url: 'https://github.com/mozilla/rust/issues/%s'
        regex: '#([0-9]+)'

  - name: 'build_ash-mozharness'
    url: 'https://hg.mozilla.org/build/ash-mozharness'

  - name: 'build_autoland'
    url: 'https://hg.mozilla.org/build/autoland'

  - name: 'build_braindump'
    url: 'https://hg.mozilla.org/build/braindump'

  - name: 'build_buildapi'
    url: 'https://hg.mozilla.org/build/buildapi'

  - name: 'build_buildbot'
    url: 'https://hg.mozilla.org/build/buildbot'

  - name: 'build_buildbot-configs'
    url: 'https://hg.mozilla.org/build/buildbot-configs'

  - name: 'build_buildbotcustom'
    url: 'https://hg.mozilla.org/build/buildbotcustom'

  - name: 'build_cloud-tools'
    url: 'https://hg.mozilla.org/build/cloud-tools'

  - name: 'build_compare-locales'
    url: 'https://hg.mozilla.org/build/compare-locales'

  - name: 'build_mozharness'
    url: 'https://hg.mozilla.org/build/mozharness'

  - name: 'build_mozpool'
    url: 'https://hg.mozilla.org/build/mozpool'

  - name: 'build_nagios-tools'
    url: 'https://hg.mozilla.org/build/nagios-tools'

  - name: 'build_opsi-package-sources'
    url: 'https://hg.mozilla.org/build/opsi-package-sources'

  - name: 'build_partner-repacks'
    url: 'https://hg.mozilla.org/build/partner-repacks'

  - name: 'build_preproduction'
    url: 'https://hg.mozilla.org/build/preproduction'

  - name: 'build_puppet'
    url: 'https://hg.mozilla.org/build/puppet'

  - name: 'build_puppet-manifests'
    url: 'https://hg.mozilla.org/build/puppet-manifests'

  - name: 'build_relabs-puppet'
    url: 'https://hg.mozilla.org/build/relabs-puppet'

  - name: 'build_relengapi'
    url: 'https://hg.mozilla.org/build/relengapi'

  - name: 'build_rpm-sources'
    url: 'https://hg.mozilla.org/build/rpm-sources'

  - name: 'build_serves3'
    url: 'https://hg.mozilla.org/build/serveS3'

  - name: 'build_slaveapi'
    url: 'https://hg.mozilla.org/build/slaveapi'

  - name: 'build_slave_health'
    url: 'https://hg.mozilla.org/build/slave_health'

  - name: 'build_talos'
    url: 'https://hg.mozilla.org/build/talos'

  - name: 'build_tools'
    url: 'https://hg.mozilla.org/build/tools'

  - name: 'build_tupperware'
    url: 'https://hg.mozilla.org/build/tupperware'

  - name: 'build_twisted'
    url: 'https://hg.mozilla.org/build/twisted'

